version: "3.4"

networks:
  backend:
    external: false
  web:
    external: true

services:
  typg:
    image: "postgres:12"
    container_name: "typg"
    environment: 
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB} 
    expose:
      - "5432"
    networks:
      - backend
    volumes:
      - dbdata:/var/lib/postgresql/data

  tyserver:
    build: 
      context: .
      dockerfile: ty-server/Dockerfile
      target: tyserver
    container_name: tyserver
    environment: 
      DATABASE_URL: ${DATABASE_URL}
      PORT: 80
    depends_on: 
      - typg
    networks:
      - web
      - backend
    labels:
      - "traefik.http.services.tyserver.loadbalancer.server.port=80" 

  tytraefik:
    image: "traefik:v2.3"
    container_name: "tytraefik"
    networks:
      - web 
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  dbdata:
