version: "3.4"
networks:
  backend:
    external: false
  web:
    external: true

services:
  typg:
    image: "postgres:12"
    container_name: "typg"
    environment: 
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB} 
    expose:
      - "5432"
    networks:
      - backend
    volumes:
      - dbdata:/var/lib/postgresql/data

  tyserver:
    build: 
      context: .
      dockerfile: ty-server/Dockerfile
      target: tyserver
    container_name: tyserver
    environment: 
      DATABASE_URL: ${DATABASE_URL}
      PORT: 80
    depends_on: 
      - typg
    networks:
      - web
      - backend
    ports:
      - "8001:80"
    restart:
      unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tyserver-web.rule=Host(`ty.paulweissenbach.com`)"
      - "traefik.http.routers.tyserver-web.entrypoints=web"
      - "traefik.port=80" 
      - "traefik.http.routers.tyserver-secured.rule=Host(`ty.paulweissenbach.com`)"
      - "traefik.http.routers.tyserver-secured.entrypoints=websecure"
      - "traefik.http.routers.tyserver-secured.tls=true"
      - "traefik.http.routers.tyserver-secured.tls.certresolver=myresolver"

  traefik:
    image: "traefik:v2.3"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
        #- "--api.insecure=true"
      - "--api.debug=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=web"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
        # - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=paul.weissenbach@aon.at"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    networks:
      - web 
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  dbdata:
