name: Relase ty

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: -p ty --release
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/ty
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}